markdown: redcarpet
permalink: /posts/:title

gems:
  - jekyll-sitemap

name: Venkat M
author: Venkata Subramanian Mahalingam
url: http://venkat.io
description: blah blah blah blog. Inside the box are many musings on life and programming!
twitter: annacoder
linkedin: annacoder
