markdown: kramdown
permalink: /posts/:title

gems:
  - jekyll-sitemap

name: Venkat M
author: Venkata Mahalingam
url: http://venkat.io
description: blah blah blah blog. Inside the box are many musings on life and programming from Venkata Mahalingam!
twitter: annacoder
linkedin: annacoder
